using Newtonsoft.Json.Linq;
using System.Text;
using QueueFramework;
using Xunit;
namespace QueueFramework.Tests;
public class BoundaryTests {
    [Fact] public void PhysicalQueueCannotBeRegisteredTwice(){var f=new Fixture();var c=f.Cmd("RegisterQueue",f.Policy());c.QueueKey="another";Assert.Equal("DUPLICATE_KEY",Assert.Throws<Fault>(()=>f.Run(c)).Code);Assert.Null(f.Store.Get("definition","another"));}
    [Fact] public void LongMailboxIdentityUsesBoundedStableBusinessKey(){var f=new Fixture();var key=new string('x',800);var id=f.Enqueue(key);Assert.Equal(id,f.Enqueue(key));var acquired=f.Acquire();Assert.Equal(64,((string)acquired["SourceKey"]!).Length);Assert.Equal(64,((string)acquired["BusinessKey"]!).Length);}
    [Fact] public void RetentionRedactsOldInputButPreservesDedupeAndRequestTombstone(){var f=new Fixture();var c=f.Cmd("Enqueue",f.Envelope());var id=(string)f.Run(c)["ItemId"]!;f.Worker().Process("mail");f.Now=f.Now.AddDays(31);f.Run(f.Cmd("ApplyRetention"));Assert.Equal("{}",f.Store.NativeGet(id)!.Input);Assert.Equal("ReplayExpired",(string)f.Run(c)["Outcome"]!);Assert.Equal(id,f.Enqueue());Assert.Single(f.Store.NativePage("mail","",100));}
    [Fact] public void RetentionPreservesReviewRequiredEvidence(){var f=new Fixture();var id=f.Enqueue();var a=f.Acquire();f.Run(f.Owned("Fail",a,new{category="Unknown",code="LOST",effect="Unknown"}));f.Now=f.Now.AddDays(31);f.Run(f.Cmd("ApplyRetention"));Assert.NotEqual("{}",f.Store.NativeGet(id)!.Input);}
    [Fact] public void PoisonItemCannotBlockFollowingValidItem(){var f=new Fixture();f.Store.NativeCreate(new NativeItem{Id=Guid.NewGuid().ToString(),Queue="mail",UniqueKey="orphan",Input="not-json",Created=f.Now.AddMinutes(-1),Available=f.Now,Expires=f.Now.AddDays(1)});f.Enqueue();Assert.Equal("ReviewRequired",(string)f.Acquire()["Outcome"]!);Assert.Equal("Acquired",(string)f.Acquire()["Outcome"]!);}
    [Fact] public void ExpiredItemCannotBeManuallyRescheduled(){var f=new Fixture();var id=f.Enqueue();var a=f.Acquire();f.Run(f.Owned("Fail",a,new{category="Unknown",code="LOST",effect="Unknown"}));f.Now=f.Now.AddDays(8);Assert.Equal("ITEM_EXPIRED",Assert.Throws<Fault>(()=>f.Run(f.Cmd("RequestRetry",new{reason="review",reconciliation="VerifiedSafe"},id,version:(long)f.Status(id)["Version"]!))).Code);}
    [Fact] public void ExpectedErrorAndAttemptEvidenceMustMatch(){var f=new Fixture();var id=(string)f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="negative",Input=f.Envelope(),ExpectedOutcome="Exception",ExpectedErrorCode="WRONG",ExpectedAttemptCount=1}}}))["RunId"]!;f.Worker(_=>new JObject()).Process("mail");Assert.Equal("Failed",(string)f.Run(f.Cmd("AdvanceTestRun",item:id))["State"]!);}
    [Fact] public void NotificationEvidenceCanBeAsserted(){var f=new Fixture();var id=(string)f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="alert",Input=f.Envelope(),ExpectedNotificationKind="Processed",ExpectedNotificationState="Pending"}}}))["RunId"]!;f.Worker().Process("mail");Assert.Equal("Passed",(string)f.Run(f.Cmd("AdvanceTestRun",item:id))["State"]!);}
    [Theory][InlineData("{\"type\":\"object\",\"properties\":[]}")][InlineData("{\"type\":\"string\",\"enum\":\"x\"}")][InlineData("{\"type\":\"number\",\"maximum\":\"large\"}")][InlineData("{\"type\":\"string\",\"minLength\":10,\"maxLength\":2}")]
    public void InvalidSchemaDefinitionsFailClosed(string schema){Assert.Equal("SCHEMA_UNSUPPORTED",Assert.Throws<Fault>(()=>Schema.CheckDefinition(JObject.Parse(schema))).Code);}
    [Fact] public void SenderContinuesPastFirstHundredTerminalEvents(){
        var f=new Fixture();for(int i=0;i<101;i++)f.Store.Add(new Row{Kind="event",Key=i.ToString("D3"),Queue="mail",Body=Json.Write(new Delivery{Id=i.ToString("D3"),State=i==100?"Pending":"Delivered",NextAttempt=f.Now})});
        Assert.Equal("NoWork",(string)f.Run(f.Cmd("ClaimEvent"))["Outcome"]!);Assert.Equal("Claimed",(string)f.Run(f.Cmd("ClaimEvent"))["Outcome"]!);
    }
    [Fact] public void WatchdogMarksMissingAttemptForReview(){var f=new Fixture();var id=f.Enqueue();var a=f.Acquire();var row=f.Store.Get("attempt",(string)a["AttemptId"]!)!;f.Store.Delete("attempt",row.Key,row.Version);f.Run(f.Cmd("RunMaintenance"));Assert.True((bool)f.Status(id)["ReviewRequired"]!);Assert.Equal("Exception",(string)f.Status(id)["Outcome"]!);}
    [Fact] public void WatchdogQuarantinesNativeProcessingItemWithoutFrameworkContext(){var f=new Fixture();var id=f.Enqueue();var native=f.Store.NativeGet(id)!;var context=f.Store.Get("itemcontext",native.UniqueKey)!;f.Store.Delete("itemcontext",context.Key,context.Version);native.Status="Processing";f.Store.NativeSet(native);var result=f.Run(f.Cmd("RunMaintenance"));Assert.Equal("Swept",(string)result["Outcome"]!);Assert.Equal(1,(int)result["Changed"]!);Assert.Equal("Exception",f.Store.NativeGet(id)!.Status);Assert.Null(f.Store.Get("itemcontext",native.UniqueKey));Assert.Empty(f.Store.Page("attempt", "mail", "", 10));}
    [Fact] public void CompletionFromAnotherQueueIsDenied(){var f=new Fixture();f.Enqueue();var a=f.Acquire();var c=f.Owned("Complete",a,new{table="qmcp_emailrequest",recordId=Guid.NewGuid().ToString()});c.QueueKey="other";var policy=f.Policy();policy.NativeQueueId=Guid.NewGuid().ToString();var p=f.Cmd("RegisterQueue",policy);p.QueueKey="other";f.Run(p);Assert.Equal("FORBIDDEN",Assert.Throws<Fault>(()=>f.Run(c)).Code);}
    [Fact] public void DeliveryLeaseCannotBeReusedAfterExpiry(){var f=new Fixture();f.Enqueue();f.Worker().Process("mail");var e=f.Run(f.Cmd("ClaimEvent"))["Event"]!;f.Now=f.Now.AddMinutes(3);Assert.Equal("STALE_DELIVERY",Assert.Throws<Fault>(()=>f.Run(f.Cmd("FinishEvent",new{eventId=(string)e["Id"]!,leaseToken=(string)e["LeaseToken"]!,accepted=true}))).Code);}
    [Fact] public void JsonObjectUsesUtf8ByteBoundary(){var prefix="{\"x\":\"";var suffix="\"}";var remaining=131072-Encoding.UTF8.GetByteCount(prefix+suffix);var exact=prefix+new string('é',remaining/2)+suffix;Assert.Equal(131072,Encoding.UTF8.GetByteCount(exact));Assert.NotNull(Json.Object(exact));Assert.Equal("INPUT_TOO_LARGE",Assert.Throws<Fault>(()=>Json.Object(prefix+new string('é',remaining/2+1)+suffix)).Code);}
    [Fact] public void JsonObjectRejectsExcessiveDepth(){var nested="{}";for(var i=0;i<32;i++)nested="{\"a\":"+nested+"}";Assert.Equal("INPUT_INVALID",Assert.Throws<Fault>(()=>Json.Object(nested)).Code);}
    [Fact] public void JsonObjectRejectsExcessiveStructuralComplexity(){var value=new JObject();for(var i=0;i<8200;i++)value["p"+i]=i;Assert.Equal("INPUT_TOO_COMPLEX",Assert.Throws<Fault>(()=>Json.Object(value.ToString(Newtonsoft.Json.Formatting.None))).Code);}
    [Fact] public void StableReferenceDigestIsCanonicalAndFixedLength(){var first=Json.Fingerprint(new JObject{{"b",2},{"a",1}});var second=Json.Fingerprint(new JObject{{"a",1},{"b",2}});Assert.Equal(64,first.Length);Assert.Matches("^[0-9a-f]{64}$",first);Assert.Equal(first,second);}
    [Fact] public void CleanupRollbackPreservesEvidenceOnDeleteFailure(){var f=new Fixture();var id=(string)f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="clean",Input=f.Envelope()}}}))["RunId"]!;f.Worker().Process("mail");f.Run(f.Cmd("AdvanceTestRun",item:id));f.Store.BeforeWrite=op=>{if(op=="delete:business")throw new Fault("DELETE_DENIED");};Assert.Throws<Fault>(()=>f.Run(f.Cmd("CleanupTestRun",item:id)));Assert.Single(f.Store.Page("business","mail","",100));}
}
