using Newtonsoft.Json.Linq;
using QueueFramework;
using QueueFramework.Simulator;
using Xunit;
namespace QueueFramework.Tests;
public sealed class Fixture {
    public readonly SimulatedStore Store;
    public readonly Engine Engine;
    public DateTime Now=new DateTime(2026,9,12,0,0,0,DateTimeKind.Utc);
    public readonly Actor Admin=new(){Id="admin",Roles=new(){"administrator"},Production=false};
    public Fixture(string? path=null){Store=new(path);Engine=new(Store,()=>Now);Setup();}
    public Command Cmd(string op,object? data=null,string item="",string attempt="",int generation=0,long version=0)=>new(){Operation=op,QueueKey="mail",RequestId=Guid.NewGuid().ToString(),DataJson=Json.Write(data??new{}),ItemId=item,AttemptId=attempt,Generation=generation,ExpectedVersion=version};
    public JObject Run(Command command,Actor? actor=null)=>JObject.Parse(Engine.Execute(command,actor??Admin));
    public QueuePolicy Policy()=>new(){NativeQueueId="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",SafeEffects=true,LeaseSeconds=10,DeadlineSeconds=60,RetryBaseSeconds=2,RetryMaxSeconds=10,Contracts=new[]{"mail.v1"},Destinations=new[]{"ops"},Grants=new(){["producer"]=new[]{"producer"},["worker"]=new[]{"worker"},["reader"]=new[]{"reader"},["retry"]=new[]{"retry"}}};
    public void Setup(){Run(Cmd("RegisterQueue",Policy()));Run(Cmd("RegisterContract",new Contract {Id="mail.v1",Schema=JObject.Parse("""{"type":"object","required":["subject","senderAddress","bodyText"],"additionalProperties":false,"properties":{"subject":{"type":"string","maxLength":100},"senderAddress":{"type":"string","maxLength":100},"bodyText":{"type":"string","maxLength":1000}}}""")}));}
    public JObject Envelope(string key="source-1")=>JObject.Parse("""{"envelopeVersion":"1.0","contract":"mail.v1","correlationId":"correlation","deduplicationKey":"SOURCE","source":{"type":"synthetic"},"payload":{"subject":"Service","senderAddress":"alex@example.com","bodyText":"Need service"}}""".Replace("SOURCE",key));
    public string Enqueue(string key="source-1")=>(string)Run(Cmd("Enqueue",Envelope(key)))["ItemId"]!;
    public JObject Acquire()=>Run(Cmd("AcquireNext"));
    public Command Owned(string op,JObject acquired,object? data=null)=>Cmd(op,data,(string)acquired["ItemId"]!,(string)acquired["AttemptId"]!,(int)acquired["Generation"]!);
    public JObject Status(string id)=>Run(Cmd("GetItemStatus",item:id));
    public ReferenceWorker Worker(Func<JObject,JObject>? extractor=null)=>new(Store,Engine,Admin,extractor??(p=>new JObject {["contact"]=p["senderAddress"],["category"]="service",["summary"]=p["subject"]}));
}
public class LifecycleTests {
    [Fact] public void DuplicateIntakeUsesOneItem(){var f=new Fixture();var a=f.Enqueue();Assert.Equal(a,f.Enqueue());Assert.Single(f.Store.NativePage("mail","",100));}
    [Fact] public void CorrelationChangeDoesNotChangeSourceIdentity(){var f=new Fixture();var id=f.Enqueue();var e=f.Envelope();e["correlationId"]="new";Assert.Equal(id,(string)f.Run(f.Cmd("Enqueue",e))["ItemId"]!);}
    [Fact] public void ContentConflictIsRejected(){var f=new Fixture();f.Enqueue();var e=f.Envelope();e["payload"]!["subject"]="Different";Assert.Equal("KEY_CONTENT_CONFLICT",Assert.Throws<Fault>(()=>f.Run(f.Cmd("Enqueue",e))).Code);}
    [Fact] public void AcquisitionReplayNeverClaimsSecondItem(){var f=new Fixture();f.Enqueue();f.Enqueue("two");var c=f.Cmd("AcquireNext");Assert.Equal(f.Run(c).ToString(),f.Run(c).ToString());Assert.Single(f.Store.NativePage("mail","",100),x=>x.Status=="Processing");}
    [Fact] public void RequestIdentityRejectsDifferentArguments(){var f=new Fixture();var c=f.Cmd("Enqueue",f.Envelope());f.Run(c);c.DataJson=Json.Write(f.Envelope("two"));Assert.Equal("REQUEST_CONFLICT",Assert.Throws<Fault>(()=>f.Run(c)).Code);}
    [Fact] public void ReceiptRollbackRestoresNativeClaim(){var f=new Fixture();f.Enqueue();f.Store.BeforeWrite=s=>{if(s=="add:command")throw new Fault("INJECTED");};Assert.Throws<Fault>(()=>f.Acquire());f.Store.BeforeWrite=null;Assert.Equal("Acquired",(string)f.Acquire()["Outcome"]!);}
    [Fact] public async Task ConcurrentAcquisitionHasOneOwner(){var f=new Fixture();f.Enqueue();var results=await Task.WhenAll(Enumerable.Range(0,20).Select(_=>Task.Run(f.Acquire)));Assert.Single(results,r=>(string?)r["Outcome"]=="Acquired");}
    [Fact] public async Task ConcurrentIdenticalRequestHasOneReceipt(){var f=new Fixture();f.Enqueue();f.Enqueue("two");var c=f.Cmd("AcquireNext");var results=await Task.WhenAll(Enumerable.Range(0,20).Select(_=>Task.Run(()=>f.Run(c).ToString())));Assert.Single(results.Distinct());}
    [Fact] public void EmptyQueueIsNormal(){var f=new Fixture();Assert.Equal("NoWork",(string)f.Acquire()["Outcome"]!);}
    [Fact] public void PausedQueueDoesNotAcquire(){var f=new Fixture();f.Enqueue();var p=f.Policy();p.Enabled=false;f.Run(f.Cmd("RegisterQueue",p,version:1));Assert.Equal("QueuePaused",(string)f.Acquire()["Outcome"]!);}
    [Fact] public void ContractIsImmutable(){var f=new Fixture();Assert.Equal("CONTRACT_IMMUTABLE",Assert.Throws<Fault>(()=>f.Run(f.Cmd("RegisterContract",new Contract{Id="mail.v1",Schema=JObject.Parse("""{"type":"string"}""")}))).Code);}
    [Fact] public void RemoteSchemaIsRejected(){var f=new Fixture();Assert.Equal("SCHEMA_UNSUPPORTED",Assert.Throws<Fault>(()=>f.Run(f.Cmd("RegisterContract",new Contract{Id="remote",Schema=JObject.Parse("""{"type":"object","$ref":"https://example.com"}""")}))).Code);}
    [Theory][InlineData("contract","unsupported")][InlineData("envelopeVersion","9.0")] public void UnsupportedEnvelopeHasNoEffects(string field,string value){var f=new Fixture();var e=f.Envelope();e[field]=value;Assert.Throws<Fault>(()=>f.Run(f.Cmd("Enqueue",e)));Assert.Empty(f.Store.NativePage("mail","",100));}
    [Fact] public void MalformedAndDuplicateJsonRejected(){var f=new Fixture();var c=f.Cmd("Enqueue");c.DataJson="""{"a":1,"a":2}""";Assert.Throws<Fault>(()=>f.Run(c));c.DataJson="not-json";Assert.Throws<Fault>(()=>f.Run(c));}
    [Fact] public void MalformedTypedCommandsUseStableFaultCodes(){var f=new Fixture();var register=f.Cmd("RegisterQueue",new {NativeQueueId="not-a-guid",Contracts=new[]{"mail.v1"},Destinations=new[]{"ops"},Grants=new Dictionary<string,string[]>{{"producer",new[]{"producer"}}}});Assert.Equal("POLICY_INVALID",Assert.Throws<Fault>(()=>f.Run(register)).Code);var contract=f.Cmd("RegisterContract",new {Id="bad",Schema="not-an-object"});Assert.Equal("SCHEMA_UNSUPPORTED",Assert.Throws<Fault>(()=>f.Run(contract)).Code);var test=f.Cmd("StartTestRun",new {cases="not-an-array"});Assert.Equal("INPUT_INVALID",Assert.Throws<Fault>(()=>f.Run(test)).Code);}
    [Fact] public void NullTestCaseFieldsAreRejected(){var f=new Fixture();var cases=new object?[]{null,new TestCase{Id="null-input",Input=null!},new TestCase{Id="null-expected",Expected=null!},new TestCase{Id=null!,Input=f.Envelope()}};foreach(var value in cases){Assert.Equal("INPUT_INVALID",Assert.Throws<Fault>(()=>f.Run(f.Cmd("StartTestRun",new{cases=new[]{value}}))).Code);}Assert.Equal("INPUT_INVALID",Assert.Throws<Fault>(()=>f.Run(f.Cmd("StartTestRun",new{cases=(object?)null})) ).Code);Assert.Empty(f.Store.Page("testrun","mail","",100));Assert.Empty(f.Store.NativePage("mail","",100));}
    [Fact] public void OversizedInputRejected(){var f=new Fixture();var c=f.Cmd("Enqueue");c.DataJson=Json.Write(new {x=new string('x',131073)});Assert.Equal("INPUT_TOO_LARGE",Assert.Throws<Fault>(()=>f.Run(c)).Code);}
    [Fact] public void ProducerCannotComplete(){var f=new Fixture();var a=new Actor{Id="producer",Roles=new(){"producer"}};Assert.Equal("FORBIDDEN",Assert.Throws<Fault>(()=>f.Run(f.Cmd("Complete"),a)).Code);}
    [Fact] public void QueueGrantRequiredEvenWithRole(){var f=new Fixture();var a=new Actor{Id="stranger",Roles=new(){"producer"}};Assert.Equal("FORBIDDEN",Assert.Throws<Fault>(()=>f.Run(f.Cmd("Enqueue",f.Envelope()),a)).Code);}
    [Fact] public void CompletionReplayHasOneIntent(){var f=new Fixture();f.Enqueue();var acquired=f.Acquire();var c=f.Owned("Complete",acquired,new{table="qmcp_emailrequest",recordId=Guid.NewGuid().ToString()});Assert.Equal(f.Run(c).ToString(),f.Run(c).ToString());Assert.Single(f.Store.Page("event","mail","",100));}
    [Theory][InlineData("Complete")][InlineData("Fail")][InlineData("Checkpoint")]public void ExpiredAttemptCannotMutate(string op){var f=new Fixture();f.Enqueue();var acquired=f.Acquire();f.Now=f.Now.AddSeconds(11);Assert.Equal("STALE_ATTEMPT",Assert.Throws<Fault>(()=>f.Run(f.Owned(op,acquired))).Code);}
    [Fact] public void CheckpointRequiresProgressAndCapsDeadline(){var f=new Fixture();f.Enqueue();var a=f.Acquire();var c=f.Owned("Checkpoint",a,new{progress="parsed"});f.Run(c);Assert.Equal("NO_PROGRESS",Assert.Throws<Fault>(()=>f.Run(f.Owned("Checkpoint",a,new{progress="parsed"}))).Code);}
    [Fact] public void DelayRequiresSweepAndDoesNotAcquireEarly(){var f=new Fixture();f.Enqueue();var a=f.Acquire();Assert.Equal("RetryScheduled",(string)f.Run(f.Owned("Fail",a,new{category="Technical",code="TRANSIENT",effect="None"}))["Outcome"]!);Assert.Equal("NoWork",(string)f.Acquire()["Outcome"]!);f.Now=f.Now.AddSeconds(4);Assert.Equal("Acquired",(string)f.Acquire()["Outcome"]!);}
    [Fact] public void SafeFailureRequeuesDirectlyWithoutExceptionNativeWrite(){var f=new Fixture();f.Enqueue();var a=f.Acquire();var writes=new List<string>();f.Store.BeforeWrite=op=>{if(op=="native:set")writes.Add(f.Store.NativePage("mail","",100).Single().Status);};Assert.Equal("RetryScheduled",(string)f.Run(f.Owned("Fail",a,new{category="Technical",code="TRANSIENT",effect="None"}))["Outcome"]!);Assert.DoesNotContain("Exception",writes);Assert.Equal("Exception",Json.Read<Attempt>(f.Store.Get("attempt",(string)a["AttemptId"]!)!.Body).Outcome);}
    [Theory][InlineData("Unknown")][InlineData("Business")]public void UncertainOrBusinessFailureRequiresReview(string category){var f=new Fixture();var id=f.Enqueue();var a=f.Acquire();Assert.Equal("ReviewRequired",(string)f.Run(f.Owned("Fail",a,new{category,code="REJECTED",effect="None"}))["Outcome"]!);Assert.True((bool)f.Status(id)["ReviewRequired"]!);}
    [Fact] public void AttemptSnapshotsPolicy(){var f=new Fixture();f.Enqueue();var a=f.Acquire();var policy=f.Policy();policy.SafeEffects=false;f.Run(f.Cmd("RegisterQueue",policy,version:1));Assert.Equal("RetryScheduled",(string)f.Run(f.Owned("Fail",a,new{category="Technical",code="TRANSIENT",effect="None"}))["Outcome"]!);}
    [Fact] public void WatchdogInvalidatesGeneration(){var f=new Fixture();var id=f.Enqueue();var a=f.Acquire();f.Now=f.Now.AddSeconds(11);f.Run(f.Cmd("RunMaintenance"));Assert.True((bool)f.Status(id)["ReviewRequired"]!);Assert.True((int)f.Status(id)["Generation"]!>(int)a["Generation"]!);}
    [Fact] public void ActiveLeaseCannotBeRecovered(){var f=new Fixture();f.Enqueue();var a=f.Acquire();Assert.Equal("LEASE_ACTIVE",Assert.Throws<Fault>(()=>f.Run(f.Owned("RecoverExpiredAttempt",a))).Code);}
    [Fact] public void StaleRetryVersionRejected(){var f=new Fixture();var id=f.Enqueue();var a=f.Acquire();f.Run(f.Owned("Fail",a,new{category="Unknown",code="LOST",effect="Unknown"}));Assert.Equal("VERSION_CONFLICT",Assert.Throws<Fault>(()=>f.Run(f.Cmd("RequestRetry",new{reason="reviewed",reconciliation="VerifiedSafe"},id,version:1))).Code);}
    [Fact] public void PostWriteRecoveryReusesBusinessRecord(){var f=new Fixture();var id=f.Enqueue();Assert.Throws<IOException>(()=>f.Worker().Process("mail",stage=>{if(stage=="after-write")throw new IOException("lost");}));f.Now=f.Now.AddSeconds(11);f.Run(f.Cmd("RunMaintenance"));var status=f.Status(id);f.Run(f.Cmd("RequestRetry",new{reason="source key reconciled",reconciliation="VerifiedSafe"},id,version:(long)status["Version"]!));f.Worker(_=>throw new Exception("must reuse")).Process("mail");Assert.Single(f.Store.Page("business","mail","",100));Assert.Equal("Processed",(string)f.Status(id)["Outcome"]!);}
    [Fact] public void InvalidExtractionNeverWrites(){var f=new Fixture();var id=f.Enqueue();f.Worker(_=>new JObject()).Process("mail");Assert.Empty(f.Store.Page("business","mail","",100));Assert.Equal("Exception",(string)f.Status(id)["Outcome"]!);}
    [Fact] public void NotificationFailurePreservesWork(){var f=new Fixture();var id=f.Enqueue();f.Worker().Process("mail");var e=f.Run(f.Cmd("ClaimEvent"))["Event"]!;f.Run(f.Cmd("FinishEvent",new{eventId=(string)e["Id"]!,leaseToken=(string)e["LeaseToken"]!,accepted=false,code="MAIL_OFFLINE"}));Assert.Equal("Processed",(string)f.Status(id)["Outcome"]!);Assert.Single(f.Store.Page("event","mail","",100));}
    [Fact] public void IntakeFailureNeedsNoQueueItem(){var f=new Fixture();f.Run(f.Cmd("ReportIntakeFailure",new{source="synthetic",correlationId="correlation",code="INVALID"}));Assert.Empty(f.Store.NativePage("mail","",100));Assert.Single(f.Store.Page("event","mail","",100));}
    [Fact] public void ProductionTestDenied(){var f=new Fixture();f.Admin.Production=true;Assert.Equal("PRODUCTION_TEST_DENIED",Assert.Throws<Fault>(()=>f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="a",Input=f.Envelope()}}}))).Code);}
    [Fact] public void TestRunUsesActualEvidenceAndCleanupIsScoped(){var f=new Fixture();var run=f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="valid",Input=f.Envelope(),Expected=JObject.Parse("""{"contact":"alex@example.com"}""")}}}));var id=(string)run["RunId"]!;f.Worker().Process("mail");Assert.Equal("Passed",(string)f.Run(f.Cmd("AdvanceTestRun",item:id))["State"]!);f.Run(f.Cmd("CleanupTestRun",item:id));Assert.Empty(f.Store.Page("business","mail","",100));}
    [Fact] public void WorkerSuccessWithoutOutputCannotPass(){var f=new Fixture();var id=(string)f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="missing",Input=f.Envelope()}}}))["RunId"]!;var a=f.Acquire();f.Run(f.Owned("Complete",a,new{table="qmcp_emailrequest",recordId=Guid.NewGuid().ToString()}));Assert.Equal("Inconclusive",(string)f.Run(f.Cmd("AdvanceTestRun",item:id))["State"]!);}
    [Fact] public void TestDeadlineIsInconclusive(){var f=new Fixture();var id=(string)f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="never-run",Input=f.Envelope()}}}))["RunId"]!;f.Now=f.Now.AddMinutes(16);Assert.Equal("Inconclusive",(string)f.Run(f.Cmd("AdvanceTestRun",item:id))["State"]!);}
    [Fact] public void FailedEvidenceCannotBeCleaned(){var f=new Fixture();var id=(string)f.Run(f.Cmd("StartTestRun",new{cases=new[]{new TestCase{Id="wrong",Input=f.Envelope(),Expected=JObject.Parse("""{"contact":"wrong"}""")}}}))["RunId"]!;f.Worker().Process("mail");f.Run(f.Cmd("AdvanceTestRun",item:id));Assert.Equal("EVIDENCE_RETENTION_HOLD",Assert.Throws<Fault>(()=>f.Run(f.Cmd("CleanupTestRun",item:id))).Code);}
    [Fact] public void RuntimeSurvivesInstanceReplacement(){var path=Path.Combine(Path.GetTempPath(),"qmcp-test-"+Guid.NewGuid()+".json");try{var f=new Fixture(path);var id=f.Enqueue();var newStore=new SimulatedStore(path);var engine=new Engine(newStore,()=>f.Now);Assert.Equal("Queued",(string)JObject.Parse(engine.Execute(f.Cmd("GetItemStatus",item:id),f.Admin))["Outcome"]!);}finally{File.Delete(path);File.Delete(path+".lock");}}
}
