using QueueFramework;
using Newtonsoft.Json.Linq;
using Xunit;
namespace QueueFramework.Tests;
public sealed class ProvenanceTests
{
    [Fact] public void PrepareCallerProvenanceIsCopiedAndCannotBeOverriddenOnAccept(){var f=new Fixture();var id=f.Enqueue();var n=f.Store.NativeGet(id)!;n.Status="Processing";f.Store.NativeSet(n);var prep=f.Cmd("PrepareAcquire",new{flowId="flow-prepared",runId="run-prepared",templateVersion="v-prepared"});var request=(string)f.Run(prep)["RequestId"]!;var accept=f.Cmd("AcceptAcquire",new{flowId="flow-attacker",runId="run-attacker",templateVersion="v-attacker"},id);accept.RequestId=request;var result=f.Run(accept);var attempt=Json.Read<Attempt>(f.Store.Get("attempt",(string)result["AttemptId"]!)!.Body);Assert.Equal("flow-prepared",(string)attempt.Caller["flowId"]!);Assert.Equal("run-prepared",(string)attempt.Caller["runId"]!);Assert.Equal("v-prepared",(string)attempt.Caller["templateVersion"]!);}
    [Fact] public void NullLegacyCallerSnapshotDefaultsToEmptyCaller(){var f=new Fixture();var id=f.Enqueue();var n=f.Store.NativeGet(id)!;n.Status="Processing";f.Store.NativeSet(n);var prep=f.Cmd("PrepareAcquire");var request=(string)f.Run(prep)["RequestId"]!;var key=Json.Hash("acquire|admin|mail");var row=f.Store.Get("cursor",key)!;var body=JObject.Parse(row.Body);body["Caller"]=JValue.CreateNull();row.Body=body.ToString(Newtonsoft.Json.Formatting.None);f.Store.Put(row,row.Version);var accept=f.Cmd("AcceptAcquire",new{flowId="attacker"},id);accept.RequestId=request;var result=f.Run(accept);var attempt=Json.Read<Attempt>(f.Store.Get("attempt",(string)result["AttemptId"]!)!.Body);Assert.Empty(attempt.Caller.Properties());}
    [Fact] public void ConsumedReplacedIntentKeepsOldAndNewReceiptsIsolated(){var f=new Fixture();var firstId=f.Enqueue("first");var firstNative=f.Store.NativeGet(firstId)!;firstNative.Status="Processing";f.Store.NativeSet(firstNative);var firstPrepare=f.Cmd("PrepareAcquire");var firstRequest=(string)f.Run(firstPrepare)["RequestId"]!;var firstAccept=f.Cmd("AcceptAcquire",new{},firstId);firstAccept.RequestId=firstRequest;var firstResult=f.Run(firstAccept);var secondId=f.Enqueue("second");var secondNative=f.Store.NativeGet(secondId)!;secondNative.Status="Processing";f.Store.NativeSet(secondNative);var secondPrepare=f.Cmd("PrepareAcquire");var secondRequest=(string)f.Run(secondPrepare)["RequestId"]!;var secondAccept=f.Cmd("AcceptAcquire",new{},secondId);secondAccept.RequestId=secondRequest;var secondResult=f.Run(secondAccept);var resolveFirst=f.Cmd("ResolveAcquire");resolveFirst.RequestId=firstRequest;var resolveSecond=f.Cmd("ResolveAcquire");resolveSecond.RequestId=secondRequest;Assert.Equal(firstId,(string)f.Run(resolveFirst)["ItemId"]!);Assert.Equal(secondId,(string)f.Run(resolveSecond)["ItemId"]!);Assert.NotEqual((string)firstResult["AttemptId"]!, (string)secondResult["AttemptId"]!);}
    [Fact] public void ExpiredUnconsumedIntentCannotResolveAsAcquiredAfterReplacement(){var f=new Fixture();var oldPrepare=f.Cmd("PrepareAcquire");var oldRequest=(string)f.Run(oldPrepare)["RequestId"]!;f.Now=f.Now.AddSeconds(11);var id=f.Enqueue("late");var native=f.Store.NativeGet(id)!;native.Status="Processing";f.Store.NativeSet(native);var newPrepare=f.Cmd("PrepareAcquire");var newRequest=(string)f.Run(newPrepare)["RequestId"]!;var accept=f.Cmd("AcceptAcquire",new{},id);accept.RequestId=newRequest;Assert.Equal("Acquired",(string)f.Run(accept)["Outcome"]!);var oldResolve=f.Cmd("ResolveAcquire");oldResolve.RequestId=oldRequest;Assert.NotEqual("Acquired",(string)f.Run(oldResolve)["Outcome"]!);var newResolve=f.Cmd("ResolveAcquire");newResolve.RequestId=newRequest;Assert.Equal("Acquired",(string)f.Run(newResolve)["Outcome"]!);}
}
