import { spawn } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { DataverseClient } from './dataverse.js';
import { root as defaultRoot } from './local.js';
const uuid=/^[a-f0-9-]{36}$/i, hash=/^[a-f0-9]{64}$/i;
function bindingCheck(binding){const client=new DataverseClient(binding,()=>null);return client.binding;}
function safeCode(error){const code=String(error?.message||error);return /^[A-Z_]{2,80}$/.test(code)?code:'DEPLOYMENT_PLAN_FAILED';}
function cliPlan(args,{root,launch}={}){return new Promise((resolve,reject)=>{const child=(launch||((argv)=>spawn('python',argv,{cwd:root,windowsHide:true,shell:false,stdio:['pipe','pipe','pipe']})))(args);let out='',done=false;const finish=(error,value)=>{if(done)return;done=true;clearTimeout(timer);error?reject(error):resolve(value)};const timer=setTimeout(()=>{child.kill?.();finish(new Error('DEPLOYMENT_PLAN_TIMEOUT'));},180000);child.on?.('error',()=>finish(new Error('DEPLOYMENT_PLAN_UNAVAILABLE')));child.stdout?.on('data',c=>{out+=c;if(Buffer.byteLength(out)>1000000){child.kill?.();finish(new Error('RESPONSE_TOO_LARGE'));}});child.stderr?.resume?.();child.on?.('close',code=>{if(code)finish(new Error('DEPLOYMENT_PLAN_FAILED'));else{try{finish(null,JSON.parse(out));}catch{finish(new Error('DEPLOYMENT_PLAN_INVALID_RESPONSE'));}}});child.stdin?.on?.('error',()=>{});child.stdin?.end?.();});}
export async function planDeployment(args={},opts={}){try{const env=opts.env||process.env, root=opts.root||defaultRoot;if(!env.QMCP_ENVIRONMENT_BINDING||!env.QMCP_DEPLOYMENT_SETTINGS)throw new Error('DEPLOYMENT_SETTINGS_REQUIRED');const binding=bindingCheck(JSON.parse(await readFile(env.QMCP_ENVIRONMENT_BINDING,'utf8')));const argv=[path.join(root,'scripts/deploy_release.py'),'--binding',path.resolve(env.QMCP_ENVIRONMENT_BINDING),'--settings',path.resolve(env.QMCP_DEPLOYMENT_SETTINGS)];const result=opts.runPlan?await opts.runPlan(argv):await cliPlan(argv,{root,launch:opts.launch});if(!result||!uuid.test(String(result.organizationId||''))||String(result.organizationId).toLowerCase()!==binding.organizationId.toLowerCase()||result.environmentUrl!==binding.environmentUrl||!hash.test(String(result.planHash||'')))throw new Error('DEPLOYMENT_PLAN_INVALID_RESPONSE');return result;}catch(error){const code=safeCode(error);throw new Error(code);}}
